### ISSUE TITLE
Filtering does not work since last Update

### ISSUE THREAD

**Issue by quotengrote** [tborychowski/miniflux-filter#4]
Hi,

on my installation the filtering do not work anymore since the Update 1.3.0.

I have nothing changed in my configuration.

## logs
```
mf-frontend  | [INFO] [API][TokenAuth] [ClientIP=172.24.0.5] User authenticated: mg  
mf-filter    | [13:23:48] [info] No items to filter out.  
mf-filter    | [13:24:18] [info] Checking filters...                               
```

## docker-compose
```
version: '3'
services:
######## Miniflux ########
  miniflux:
    container_name: "mf-frontend"
    image: miniflux/miniflux:latest
    restart: always
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://miniflux:XXX@mf-db/miniflux?sslmode=disable
      - RUN_MIGRATIONS=1
#      - CREATE_ADMIN=1
#      - ADMIN_USERNAME=XXX
#      - ADMIN_PASSWORD=XXX
      - WORKER_POOL_SIZE=10
      - POLLING_FREQUENCY=10
      - CLEANUP_ARCHIVE_UNREAD_DAYS=-1
      - CLEANUP_ARCHIVE_READ_DAYS=90
      - TZ=Europe/Berlin
    networks:
      - miniflux_intern
      - proxy
    labels:
      - traefik.http.routers.miniflux.rule=Host(`miniflux.XXX.net`)
      - traefik.enable=true
      - traefik.http.routers.miniflux.tls=true
      - traefik.http.routers.miniflux.tls.certresolver=resolver_letsencrypt
      - traefik.http.routers.miniflux.entrypoints=websecure
      - traefik.http.services.miniflux.loadbalancer.server.port=8080
######## PostGreSQL ########
  db:
    container_name: "mf-db"
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=XXX
      - POSTGRES_PASSWORD=XXX
      - TZ=Europe/Berlin
    volumes:
      - miniflux-db:/var/lib/postgresql/data
    networks:
      - miniflux_intern
    labels:
      - com.centurylinklabs.watchtower.enable=false
######## Miniflux-Filter ########
  filter:
    container_name: "mf-filter"
    image: tborychowski/miniflux-filter:1.3.0
    restart: always
    depends_on:
      - miniflux
    environment:
      - HOST=http://mf-frontend:8080/
      - API_KEY=XXX
      - CHECK_EVERY_S=30 # 300 seconds = 5 min
      - TZ=Europe/Berlin
    volumes:
      #- ./logs:/app/logs
      - ./filters.yml:/app/filters.yml
    networks:
      - miniflux_intern
      # vorher API-Schlüssel in miniflux generieren und hier eintragen
######## RSS-Bridge ########
  rssbridge:
    container_name: "mf-bridge"
    image: rssbridge/rss-bridge:latest
    restart: always
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./whitelist.txt:/app/whitelist.txt
    networks:
      - miniflux_intern
    ports: #um neue Feeds einzufügen
      - 3001:80


######## Volumes ########
volumes:
  miniflux-db:
######## Networks ########
networks:
  proxy:
    external: true
  miniflux_intern:
    driver: bridge

```

## filters
```
filters:
  - url: 'https://www.heise.de/'
    title: 'heise+ |'
  - url: 'https://www.heise.de/'
    title: 'Kurz informiert:'
  - url: 'https://www.heise.de/'
    title: 'SoftwareArchitekTOUR, Episode'
  - url: 'https://www.heise.de/'
    title: 'TechStage | '
  - url: 'https://www.heise.de/'
    title: 'Podcast "Die Hupe": '
  - url: 'https://www.heise.de/'
    title: 'heise-Angebot: '
  - url: 'https://www.heise.de/'
    title: 'TGIQF'
  - url: 'https://www.heise.de/'
    title: 'Was war. Was wird.'
  - url: 'https://www.heise.de/'
    title: 'TechStage | '
  - url: 'https://www.heise.de/'
    title: 'uplink'
  - url: 'https://www.heise.de/'
    title: 'Die Bilder der Woche (KW'
  - url: 'https://www.heise.de/'
    title: 'Missing Link:'
  - url: 'https://www.heise.de/'
    title: 'heiseshow'
  - url: 'https://www.heise.de/'
    title: 'Heise spielt'
  - url: 'https://www.heise.de/'
    title: 't zockt'
  - url: 'https://www.heise.de/'
    title: '#heiseshow:'
  - url: 'https://www.heise.de/'
    title: 'Anzeige:'

  - url: 'http://toonhole.com'
    title: 'Bernai'

  - url: 'https://www.golem.de/'
    title: 'Sonst noch was?'
  - url: 'https://www.golem.de/'
    title: 'Anzeige: '

  - url: 'https://www.axios.com/'
    title: 'Podcast: '
  - url: 'https://www.axios.com/'
    title: 'Axios on HBO'

  - url: 'https://stadt-bremerhaven.de'
    title: 'Immer wieder sonntags KW'
  - url: 'https://stadt-bremerhaven.de'
    title: 'Disney+'
  - url: 'https://stadt-bremerhaven.de'
    title: 'Sky Ticket'

  - url: 'https://netzpolitik.org'
    title: 'NPP '

  - url: 'https://www.planet3dnow.de'
    title: 'DesktopOK'
  - url: 'https://www.planet3dnow.de'
    title: 'Nvidia GeForce-Treiber'
  - url: 'https://www.planet3dnow.de'
    title: 'HWiNFO64'
  - url: 'https://www.planet3dnow.de'
    title: 'Radeon Software Adrenalin'
  - url: 'https://www.planet3dnow.de'
    title: 'WinRAR'
  - url: 'https://www.planet3dnow.de'
    title: 'MC Extractor'
  - url: 'https://www.planet3dnow.de'
    title: 'FurMark'
  - url: 'https://www.planet3dnow.de'
    title: 'Thunderbird'
  - url: 'https://www.planet3dnow.de'
    title: 'PowerToys v'
  - url: 'https://www.planet3dnow.de'
    title: 'WinSCP'
  - url: 'https://www.planet3dnow.de'
    title: 'GPU‑Z'
  - url: 'https://www.planet3dnow.de'
    title: 'Blender'
  - url: 'https://www.planet3dnow.de'
    title: 'Process Lasso'
  - url: 'https://www.planet3dnow.de'
    title: 'Rufus'
  - url: 'https://www.planet3dnow.de'
    title: 'AIDA64 Version'
  - url: 'https://www.planet3dnow.de'
    title: 'CrystalDiskMark'
  - url: 'https://www.planet3dnow.de'
    title: 'CrystalDiskInfo'
  - url: 'https://www.planet3dnow.de'
    title: 'System Information Viewer Version'
  - url: 'https://www.planet3dnow.de'
    title: 'LibreOffice 7'
  - url: 'https://www.planet3dnow.de'
    title: 'Universal Media Server'
  - url: 'https://www.planet3dnow.de'
    title: 'FreeCommander XE'
  - url: 'https://www.planet3dnow.de'
    title: 'Notepad++'
  - url: 'https://www.planet3dnow.de'
    title: 'ZenTimings'
  - url: 'https://www.planet3dnow.de'
    title: 'Prime95'
  - url: 'https://www.planet3dnow.de'
    title: 'NVCleanstall v'
  - url: 'https://www.planet3dnow.de'
    title: 'KiTTY'
  - url: 'https://www.planet3dnow.de'
    title: 'Sysinternals Suite'
  - url: 'https://www.planet3dnow.de'
    title: 'Display Driver Uninstaller (DDU)'
  - url: 'https://www.planet3dnow.de'
    title: 'paint.net'
  - url: 'https://www.planet3dnow.de'
    title: 'DesktopOK'
  - url: 'https://www.planet3dnow.de'
    title: 'Ryzen Master'
  - url: 'https://www.planet3dnow.de'
    title: 'Media Player Classic'
  - url: 'https://www.planet3dnow.de'
    title: 'Quick CPU'
  - url: 'https://www.planet3dnow.de'
    title: 'SystemRescue'

  - url: 'https://www.monkeyuser.com'
    title: 'AdLitteram'

  - url: 'https://www.computerbase.de'
    title: 'Adrenalin 2020 Edition'
  - url: 'https://www.computerbase.de'
    title: 'Adrenalin 2021 Edition'

  - url: 'https://www.sueddeutsche.de'
    title: 'Bundesliga'
  - url: 'https://www.sueddeutsche.de'
    content: 'Formel 1'
  - url: 'https://www.sueddeutsche.de'
    title: 'Formel-1'
  - url: 'https://www.sueddeutsche.de'
    title: 'Bayern'
  - url: 'https://www.sueddeutsche.de'
    title: 'BVB'
  - url: 'https://www.sueddeutsche.de'
    title: 'Schalke'
  - url: 'https://www.sueddeutsche.de'
    title: '"Tatort"'
  - url: 'https://www.sueddeutsche.de'
    title: 'Lewandowski'
  - url: 'https://www.sueddeutsche.de'
    title: 'Leverkusen'
  - url: 'https://www.sueddeutsche.de'
    title: 'Tabellenspitze'
  - url: 'https://www.sueddeutsche.de'
    title: 'Formel-1'
  - url: 'https://www.sueddeutsche.de'
    title: 'Werder'
  - url: 'https://www.sueddeutsche.de'
    title: 'Frankfurt'
  - url: 'https://www.sueddeutsche.de'
    title: 'Trikots'
  - url: 'https://www.sueddeutsche.de'
    title: 'Tuchel'
  - url: 'https://www.sueddeutsche.de'
    title: 'Klopp'
  - url: 'https://www.sueddeutsche.de'
    title: 'La Liga'
  - url: 'https://www.sueddeutsche.de'
    title: 'DFB-Pokal'
  - url: 'https://www.sueddeutsche.de'
    title: 'Elfmeter'
  - url: 'https://www.sueddeutsche.de'
    title: 'Toni Kroos'
  - url: 'https://www.sueddeutsche.de'
    title: 'Real Madrid'
  - url: 'https://www.sueddeutsche.de'
    title: 'HSV'
  - url: 'https://www.sueddeutsche.de'
    title: 'Derby'
  - url: 'https://www.sueddeutsche.de'
    title: 'Hertha'
  - url: 'https://www.sueddeutsche.de'
    title: 'Premier'
  - url: 'https://www.sueddeutsche.de'
    title: 'Hertha'
  - url: 'https://www.sueddeutsche.de'
    title: 'Berlinale'
  - url: 'https://www.sueddeutsche.de'
    title: 'Nordische Ski-WM'
  - url: 'https://www.sueddeutsche.de'
    title: 'Skispringen'
  - url: 'https://www.sueddeutsche.de'
    title: 'Borussia'
  - url: 'https://www.sueddeutsche.de'
    title: 'Ronaldo'
  - url: 'https://www.sueddeutsche.de'
    title: 'Champions League'
  - url: 'https://www.sueddeutsche.de'
    title: 'Bundestrainer'
  - url: 'https://www.sueddeutsche.de'
    title: 'Juve'
  - url: 'https://www.sueddeutsche.de'
    title: 'Champions-League'
  - url: 'https://www.sueddeutsche.de'
    title: 'BVB'
  - url: 'https://www.sueddeutsche.de'
    title: 'FC Sevilla'
  - url: 'https://www.sueddeutsche.de'
    title: 'Joachim Löw'
  - url: 'https://www.sueddeutsche.de'
    title: 'Gladbach'
  - url: 'https://www.sueddeutsche.de'
    content: 'Fußball'
  - url: 'https://www.sueddeutsche.de'
    content: 'Fussball'
  - url: 'https://www.sueddeutsche.de'
    title: 'OSC Lille'
  - url: 'https://www.sueddeutsche.de'
    title: 'DFB'
  - url: 'https://www.sueddeutsche.de'
    content: 'SZ-Plus-Abonnenten lesen auch'

```
## opml
```
<?xml version="1.0" encoding="UTF-8"?>
    <opml version="2.0">
        <body>
            <outline text="All">
                <outline title="Augen geradeaus!" text="Augen geradeaus!" xmlUrl="https://augengeradeaus.wordpress.com/feed/" htmlUrl="https://augengeradeaus.wordpress.com"></outline>
                <outline title="SPARTANAT" text="SPARTANAT" xmlUrl="https://www.spartanat.com/feed/" htmlUrl="https://www.spartanat.com"></outline>
                <outline title="The Crow" text="The Crow" xmlUrl="https://thecrow.uk/feed.xml" htmlUrl="https://thecrow.uk/"></outline>
                <outline title="AGDT" text="AGDT" xmlUrl="https://www.diabetes-technologie.de/feed/" htmlUrl="https://www.diabetes-technologie.de"></outline>
                <outline title="Arms Control Wonk" text="Arms Control Wonk" xmlUrl="http://feeds.feedburner.com/acw/" htmlUrl="https://www.armscontrolwonk.com"></outline>
                <outline title="Augen geradeaus!" text="Augen geradeaus!" xmlUrl="https://augengeradeaus.net/feed/atom/" htmlUrl="https://augengeradeaus.net"></outline>
                <outline title="Axios" text="Axios" xmlUrl="https://api.axios.com/feed/top/" htmlUrl="https://www.axios.com/top/"></outline>
                <outline title="beaver_bladeworks - Instagram Bridge" text="beaver_bladeworks - Instagram Bridge" xmlUrl="http://mf-bridge/?action=display&amp;bridge=Instagram&amp;context=Username&amp;direct_links=on&amp;format=Mrss&amp;media_type=all&amp;u=beaver_bladeworks" htmlUrl="https://www.instagram.com/beaver_bladeworks/"></outline>
                <outline title="bit-booster" text="bit-booster" xmlUrl="http://bit-booster.blogspot.com/feeds/posts/default?alt=rss" htmlUrl="http://bit-booster.blogspot.com/"></outline>
                <outline title="Cabin Porn" text="Cabin Porn" xmlUrl="https://cabinporn.com/rss" htmlUrl="https://cabinporn.com/"></outline>
                <outline title="Caschys Blog" text="Caschys Blog" xmlUrl="http://feeds2.feedburner.com/stadt-bremerhaven/dqXM" htmlUrl="https://stadt-bremerhaven.de"></outline>
                <outline title="Chris Custom Works" text="Chris Custom Works" xmlUrl="https://chriscustomworks.com/feed/" htmlUrl="https://chriscustomworks.com"></outline>
                <outline title="Colossal" text="Colossal" xmlUrl="http://feeds.feedburner.com/colossal" htmlUrl="https://www.thisiscolossal.com"></outline>
                <outline title="Comics – Toggl Blog" text="Comics – Toggl Blog" xmlUrl="https://toggl.com/blog/tag/comics/feed" htmlUrl="https://toggl.com/blog"></outline>
                <outline title="CommitStrip" text="CommitStrip" xmlUrl="https://www.commitstrip.com/en/feed/" htmlUrl="https://www.commitstrip.com"></outline>
                <outline title="ComputerBase" text="ComputerBase" xmlUrl="https://www.computerbase.de/rss/news.xml" htmlUrl="https://www.computerbase.de/"></outline>
                <outline title="Deutschland" text="Deutschland" xmlUrl="https://www.volksstimme.de/section/rss&amp;Profile=1123&amp;UseProfile=1&amp;Title=Deutschland&amp;ParagraphCount=99" htmlUrl="https://www.volksstimme.de/rss"></outline>
                <outline title="devconnected" text="devconnected" xmlUrl="https://devconnected.com/feed/" htmlUrl="https://devconnected.com"></outline>
                <outline title="DevOps Dudes - Medium" text="DevOps Dudes - Medium" xmlUrl="https://medium.com/feed/devops-dudes" htmlUrl="https://medium.com/devops-dudes?source=rss----c07d41d748a0---4"></outline>
                <outline title="Die Gewissensfrage - SZ-Magazin" text="Die Gewissensfrage - SZ-Magazin" xmlUrl="https://sz-magazin.sueddeutsche.de/rss/tag/die-gewissensfrage" htmlUrl="https://sz-magazin.sueddeutsche.de/tag/die-gewissensfrage"></outline>
                <outline title="Dilbert Daily Strip" text="Dilbert Daily Strip" xmlUrl="http://feed.dilbert.com/dilbert/daily_strip" htmlUrl="http://dilbert.com"></outline>
                <outline title="EleFacts" text="EleFacts" xmlUrl="https://www.elefacts.de/feed.rss" htmlUrl="https://www.elefacts.de"></outline>
                <outline title="✍ Evan Travers" text="✍ Evan Travers" xmlUrl="http://evantravers.com/feed.xml" htmlUrl="http://evantravers.com"></outline>
                <outline title="Explosm" text="Explosm" xmlUrl="http://feeds.feedburner.com/Explosm" htmlUrl="http://explosm.net"></outline>
                <outline title="Extra Ordinary" text="Extra Ordinary" xmlUrl="https://www.exocomics.com/feed" htmlUrl="https://www.exocomics.com"></outline>
                <outline title="Fefes Blog" text="Fefes Blog" xmlUrl="http://blog.fefe.de/rss.xml?html" htmlUrl="http://blog.fefe.de/"></outline>
                <outline title="Finanztip.de" text="Finanztip.de" xmlUrl="https://www.finanztip.de/sitemap.xml?cHash=a9b4ae9ad775d577cdd3cb1d01e5aadf&amp;sitemap=rssFeedAllPages" htmlUrl="https://www.finanztip.de/"></outline>
                <outline title="FSV Merseburg e.V. - Beiträge | Facebook" text="FSV Merseburg e.V. - Beiträge | Facebook" xmlUrl="http://mf-bridge/?action=display&amp;bridge=Facebook&amp;context=User&amp;format=Mrss&amp;limit=-1&amp;media_type=novideo&amp;u=166633753386419" htmlUrl="https://www.facebook.com/166633753386419/posts?_fb_noscript=1"></outline>
                <outline title="Golem.de" text="Golem.de" xmlUrl="http://rss.golem.de/rss.php?feed=RSS1.0" htmlUrl="https://www.golem.de/"></outline>
                <outline title="heise online News" text="heise online News" xmlUrl="https://www.heise.de/rss/heise.rdf" htmlUrl="https://www.heise.de/"></outline>
                <outline title="Invisible Bread" text="Invisible Bread" xmlUrl="http://feeds.feedburner.com/InvisibleBread" htmlUrl="http://invisiblebread.com"></outline>
                <outline title="Jake Likes Onions" text="Jake Likes Onions" xmlUrl="https://jakelikesonions.com/rss" htmlUrl="https://jakelikesonions.com/"></outline>
                <outline title="Josef Adamčík" text="Josef Adamčík" xmlUrl="https://josef-adamcik.cz/feed.xml" htmlUrl="https://josef-adamcik.cz/"></outline>
                <outline title="kamon_knives - Instagram Bridge" text="kamon_knives - Instagram Bridge" xmlUrl="http://mf-bridge/?action=display&amp;bridge=Instagram&amp;context=Username&amp;direct_links=on&amp;format=Mrss&amp;media_type=all&amp;u=kamon_knives" htmlUrl="https://www.instagram.com/kamon_knives/"></outline>
                <outline title="Klassik Memes | Facebook" text="Klassik Memes | Facebook" xmlUrl="http://mf-bridge/?action=display&amp;bridge=Facebook&amp;context=User&amp;format=Mrss&amp;limit=-1&amp;media_type=novideo&amp;skip_reviews=on&amp;u=klassikmemes" htmlUrl="https://www.facebook.com/klassikmemes/posts?_fb_noscript=1"></outline>
                <outline title="Kulturkalender-JL" text="Kulturkalender-JL" xmlUrl="https://kulturkalender-jl.de/feed/" htmlUrl="https://kulturkalender-jl.de"></outline>
                <outline title="law blog" text="law blog" xmlUrl="https://www.lawblog.de/feed/" htmlUrl="https://www.lawblog.de"></outline>
                <outline title="Lexikaliker" text="Lexikaliker" xmlUrl="https://www.lexikaliker.de/feed/" htmlUrl="https://www.lexikaliker.de"></outline>
                <outline title="lxkr" text="lxkr" xmlUrl="https://www.lxkr.de/feed/" htmlUrl="https://www.lxkr.de"></outline>
                <outline title="Magdeburg" text="Magdeburg" xmlUrl="https://www.volksstimme.de/section/rss&amp;Profile=1020&amp;UseProfile=1&amp;Title=Magdeburg" htmlUrl="https://www.volksstimme.de/rss"></outline>
                <outline title="Mandatory Roller Coaster" text="Mandatory Roller Coaster" xmlUrl="https://mandatoryrollercoaster.com/rss" htmlUrl="https://mandatoryrollercoaster.com/"></outline>
                <outline title="Masterzen&amp;#39;s Blog" text="Masterzen&amp;#39;s Blog" xmlUrl="http://feeds.feedburner.com/masterzen" htmlUrl="http://www.masterzen.fr/"></outline>
                <outline title="MikroTik blog" text="MikroTik blog" xmlUrl="https://blog.mikrotik.com/rss/" htmlUrl="https://blog.mikrotik.com/"></outline>
                <outline title="MonkeyUser" text="MonkeyUser" xmlUrl="https://www.monkeyuser.com/feed.xml" htmlUrl="https://www.monkeyuser.com"></outline>
                <outline title="Moonbeard" text="Moonbeard" xmlUrl="https://moonbeard.com/feed/" htmlUrl="https://moonbeard.com"></outline>
                <outline title="Mr. Lovenstein" text="Mr. Lovenstein" xmlUrl="https://www.mrlovenstein.com/rss.xml" htmlUrl="http://mrlovenstein.com"></outline>
                <outline title="Nedroid Picture Diary 2" text="Nedroid Picture Diary 2" xmlUrl="http://nedroid.com/feed/" htmlUrl="http://nedroid.com"></outline>
                <outline title="Netflix TechBlog - Medium" text="Netflix TechBlog - Medium" xmlUrl="https://netflixtechblog.com/feed" htmlUrl="https://netflixtechblog.com?source=rss----2615bd06b42e---4"></outline>
                <outline title="Netzfrequenz.info" text="Netzfrequenz.info" xmlUrl="https://www.netzfrequenz.info/feed" htmlUrl="https://www.netzfrequenz.info"></outline>
                <outline title="netzpolitik.org" text="netzpolitik.org" xmlUrl="https://netzpolitik.org/feed/" htmlUrl="https://netzpolitik.org"></outline>
                <outline title="Planet 3DNow!" text="Planet 3DNow!" xmlUrl="http://www.planet3dnow.de/cms/feed/" htmlUrl="https://www.planet3dnow.de/cms"></outline>
                <outline title="Poorly Drawn Lines" text="Poorly Drawn Lines" xmlUrl="http://feeds.feedburner.com/PoorlyDrawnLines" htmlUrl="http://www.poorlydrawnlines.com"></outline>
                <outline title="Richtersicht" text="Richtersicht" xmlUrl="https://richtersicht.de/feed/" htmlUrl="https://richtersicht.de"></outline>
                <outline title="Sachsen-Anhalt" text="Sachsen-Anhalt" xmlUrl="https://www.volksstimme.de/section/rss&amp;Profile=1018&amp;UseProfile=1&amp;Title=Sachsen-Anhalt&amp;ParagraphCount=99" htmlUrl="https://www.volksstimme.de/rss"></outline>
                <outline title="Safely Endangered" text="Safely Endangered" xmlUrl="https://www.safelyendangered.com/feed/" htmlUrl="https://www.safelyendangered.com"></outline>
                <outline title="Saturday Morning Breakfast Cereal" text="Saturday Morning Breakfast Cereal" xmlUrl="https://www.smbc-comics.com/comic/rss" htmlUrl="https://www.smbc-comics.com/"></outline>
                <outline title="scinexx | Das Wissensmagazin" text="scinexx | Das Wissensmagazin" xmlUrl="http://feeds.feedburner.com/scinexx" htmlUrl="https://www.scinexx.de"></outline>
                <outline title="ServeTheHome" text="ServeTheHome" xmlUrl="http://feeds.feedburner.com/ServeTheHome" htmlUrl="https://www.servethehome.com"></outline>
                <outline title="Shady Characters" text="Shady Characters" xmlUrl="http://feeds.feedburner.com/ShadyCharacters" htmlUrl="https://shadycharacters.co.uk"></outline>
                <outline title="splitkb.com Blog - Everything split keyboard." text="splitkb.com Blog - Everything split keyboard." xmlUrl="https://blog.splitkb.com/blog?format=rss" htmlUrl="https://blog.splitkb.com/"></outline>
                <outline title="sticky comics" text="sticky comics" xmlUrl="http://www.stickycomics.com/feed/" htmlUrl="https://www.stickycomics.com"></outline>
                <outline title="Stories by Erez Zukerman on Medium" text="Stories by Erez Zukerman on Medium" xmlUrl="https://medium.com/feed/@ezuk" htmlUrl="https://medium.com/@ezuk?source=rss-300cac6132f6------2"></outline>
                <outline title="Techniktagebuch" text="Techniktagebuch" xmlUrl="https://techniktagebuch.tumblr.com/rss" htmlUrl="https://techniktagebuch.tumblr.com/"></outline>
                <outline title="The Bartleby" text="The Bartleby" xmlUrl="https://thebartleby.com/feed/" htmlUrl="https://thebartleby.com"></outline>
                <outline title="the darnedest thing" text="the darnedest thing" xmlUrl="http://thedarnedestthing.com/atom.xml" htmlUrl="http://thedarnedestthing.com/"></outline>
                <outline title="The New Stack" text="The New Stack" xmlUrl="https://thenewstack.io/feed/" htmlUrl="https://thenewstack.io"></outline>
                <outline title="they can talk" text="they can talk" xmlUrl="https://theycantalk.com/rss" htmlUrl="https://theycantalk.com/"></outline>
                <outline title="Thomas Baart" text="Thomas Baart" xmlUrl="https://thomasbaart.nl/feed/" htmlUrl="https://thomasbaart.nl"></outline>
                <outline title="Toonhole" text="Toonhole" xmlUrl="http://feeds.feedburner.com/Toonhole" htmlUrl="http://toonhole.com"></outline>
                <outline title="Topthemen - SZ.de" text="Topthemen - SZ.de" xmlUrl="https://rss.sueddeutsche.de/rss/Topthemen" htmlUrl="https://www.sueddeutsche.de"></outline>
                <outline title="Twitter @isfies666" text="Twitter @isfies666" xmlUrl="http://mf-bridge/?action=display&amp;bridge=Twitter&amp;context=By+username&amp;format=Mrss&amp;nopic=on&amp;norep=on&amp;u=isfies666" htmlUrl="https://twitter.com/isfies666"></outline>
                <outline title="Wikipedia - Beobachtungsliste [de]" text="Wikipedia - Beobachtungsliste [de]" xmlUrl="https://de.wikipedia.org/w/api.php?action=feedwatchlist&amp;allrev=1&amp;feedformat=atom&amp;wlowner=Quotengrote&amp;wltoken=5afaf0ad7ab651eaff83078414fc5ef6eb4213bc" htmlUrl="https://de.wikipedia.org/wiki/Spezial:Beobachtungsliste"></outline>
                <outline title="Working The Angles - Beiträge | Facebook" text="Working The Angles - Beiträge | Facebook" xmlUrl="http://mf-bridge/?action=display&amp;bridge=Facebook&amp;context=User&amp;format=Mrss&amp;limit=-1&amp;media_type=novideo&amp;skip_reviews=on&amp;u=workingtheangles" htmlUrl="https://www.facebook.com/workingtheangles/posts?_fb_noscript=1"></outline>
                <outline title="Wumo" text="Wumo" xmlUrl="http://wumo.com/wumo?view=rss" htmlUrl="http://wumo.com/wumo"></outline>
                <outline title="Xerxes-Knives" text="Xerxes-Knives" xmlUrl="https://www.xerxes-knives-shop.com/index.rss" htmlUrl="https://www.xerxes-knives-shop.com/"></outline>
                <outline title="xerxes.knives - Instagram Bridge" text="xerxes.knives - Instagram Bridge" xmlUrl="http://mf-bridge/?action=display&amp;bridge=Instagram&amp;context=Username&amp;direct_links=on&amp;format=Mrss&amp;media_type=all&amp;u=xerxes.knives" htmlUrl="https://www.instagram.com/xerxes.knives/"></outline>
                <outline title="xkcd" text="xkcd" xmlUrl="https://xkcd.com/rss.xml" htmlUrl="https://xkcd.com/"></outline>
                <outline title="ZeroAir Reviews" text="ZeroAir Reviews" xmlUrl="https://zeroair.org/feed/" htmlUrl="https://zeroair.org"></outline>
            </outline>
        </body>
    </opml>
```
