### ISSUE TITLE
Entries don't get marked as read

### ISSUE THREAD

**Issue by quotengrote** [tborychowski/miniflux-filter#6]
Hi,

time for a new problem... ;-)

Today miniflux-filter stopped marking entries as read.

  - Filter-List: https://pastebin.com/cpM4DxjG

A few messages that should get marked:

  - "heise-Angebot: IT-Sicherheitstag beleuchtet das Zusammenspiel von KI und Cybersicherheit"
  - "heise+ | Prognose: So entwickelt sich der IT-Arbeitsmarkt" 

Feed: https://www.heise.de/rss/heise.rdf

happens every few weeks, normally restarting the container fixes that probem, but not that time.

Let me know if you need more infos/ or a account to check things...

thx
mg

**Comment by tborychowski** [comment]
You might be a bit overzealous with your filters. 
Just for these 2 - you have:
```yml
filters:
  - url: 'https://www.heise.de/'
    title: 'heise-Angebot'
  - url: 'https://www.heise.de/'
    title: 'heise-Angebot:'
  - url: 'https://www.heise.de/'
    title: 'heise-Angebot:'
  - url: 'https://www.heise.de/'
    title: 'heise-Angebot:'
  - url: 'https://www.heise.de/'
    title: 'heise-Angebot:'
  - url: 'https://www.heise.de/'
    content: 'heise-Angebot'
  - url: 'https://www.heise.de/'
    content: 'heise-Angebot:'

  - url: 'https://www.heise.de/'
    content: 'heise+ |'
  - url: 'https://www.heise.de/'
    content: 'heise+ |'
  - url: 'https://www.heise.de/'
    title: 'heise+ |'
  - url: 'https://www.heise.de/'
    title: 'heise+ |'
  - url: 'https://www.heise.de/'
    title: 'heise+ | '
  - url: 'https://www.heise.de/'
    title: 'heise+ | '
  - url: 'https://www.heise.de/'
    title: 'heise+ | '
  - url: 'https://www.heise.de/'
    title: 'heise+'
  - url: 'https://www.heise.de/'
    title: 'heise+ | '
  - url: 'https://www.heise.de/'
    title: 'heise+'
```

(unless you pasted your filters 10 times in the pastebin).

You only need to "match" the filter once:
```yml
filters:
  - url: 'heise.de'
    title: 'heise-Angebot'
  - url: 'heise.de'
    content: 'heise-Angebot'

  - url: 'heise.de'
    title: 'heise+'
  - url: 'heise.de'
    content: 'heise+'
```


I'll have a look.
